services:
  postgres:
    image: postgres:16-alpine
    container_name: uni_help_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-uni_help}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-uni_help_pass}
      POSTGRES_DB: ${POSTGRES_DB:-uni_help}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-uni_help}']
      interval: 10s
      timeout: 5s
      retries: 5



  backend:
    image: backend-test
    container_name: uni_help_backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-uni_help}:${POSTGRES_PASSWORD:-uni_help_pass}@postgres:5432/${POSTGRES_DB:-uni_help}
      JWT_SECRET: ${JWT_SECRET:-super_secret_jwt_key_change_in_prod}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      PORT: 3001
    ports:
      - '3001:3001'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: uni_help_frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3001}
    ports:
      - '3000:3000'

volumes:
  postgres_data:
